/**
 * Generates prisma/migrations/20261010120000_normalize_country_codes/migration.sql.
 *
 * Builds a value -> code table from every allowed code (src/common/geo/countries.ts):
 *   - the code itself, any case ("ar")
 *   - Intl.DisplayNames in en, es and fr, plus accent-free variants ("espana")
 *   - manual aliases for the UK home nations (Intl has no names for GB-ENG/SCT/WLS)
 *   - flag emojis (regional indicators, or tag sequences for the home nations),
 *     matched as a prefix so "🇪🇸 España" also maps
 * and writes it as VALUES inside the migration so it is reproducible in any
 * environment. Fails if one key would map to two different codes.
 *
 * Run: npx ts-node prisma/scripts/generate-country-mapping.ts
 */
import { writeFileSync } from "fs";
import { join } from "path";
import { COUNTRY_CODES, UK_HOME_NATIONS } from "../../src/common/geo/countries";

const MIGRATION = "20261010120000_normalize_country_codes";
const LOCALES = ["en", "es", "fr"];

const HOME_NATION_ALIASES: Record<(typeof UK_HOME_NATIONS)[number], string[]> = {
  "GB-ENG": ["England", "Inglaterra", "Angleterre"],
  "GB-SCT": ["Scotland", "Escocia", "Écosse"],
  "GB-WLS": ["Wales", "Gales", "Pays de Galles"],
};

function stripAccents(value: string): string {
  return value.normalize("NFD").replace(/\p{M}/gu, "");
}

/** Same normalization the SQL applies to stored values: lower(btrim(normalize(value, NFC))). */
function toKey(value: string): string {
  return value.normalize("NFC").trim().toLowerCase();
}

function flagFor(code: string): string {
  if (code.length === 2) {
    return [...code].map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65)).join("");
  }
  // Tag sequence: black flag + tag letters of "gbeng" + cancel tag
  const tags = [...code.replace("-", "").toLowerCase()].map((c) =>
    String.fromCodePoint(0xe0000 + c.charCodeAt(0)),
  );
  return `\u{1F3F4}${tags.join("")}\u{E007F}`;
}

function namesFor(code: string): string[] {
  if (code in HOME_NATION_ALIASES) {
    return HOME_NATION_ALIASES[code as keyof typeof HOME_NATION_ALIASES];
  }
  return LOCALES.map((locale) =>
    new Intl.DisplayNames([locale], { type: "region", fallback: "none" }).of(code),
  ).filter((name): name is string => Boolean(name));
}

function buildKeyMap(): Map<string, string> {
  const map = new Map<string, string>();
  const conflicts: string[] = [];
  const add = (key: string, code: string) => {
    const existing = map.get(key);
    if (existing && existing !== code) conflicts.push(`"${key}": ${existing} vs ${code}`);
    map.set(key, code);
  };
  for (const code of COUNTRY_CODES) {
    add(toKey(code), code);
    for (const name of namesFor(code)) {
      add(toKey(name), code);
      add(toKey(stripAccents(name)), code);
    }
  }
  if (conflicts.length) throw new Error(`Ambiguous country keys:\n${conflicts.join("\n")}`);
  return map;
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function valuesList(rows: [string, string][]): string {
  return rows.map(([a, b]) => `  (${sqlString(a)}, ${sqlString(b)})`).join(",\n");
}

function updateFor(table: string, blankToNull: boolean): string {
  const lookup = `COALESCE(
        (SELECT k.code FROM country_key_map k WHERE k.key = lower(btrim(normalize(t."country", NFC)))),
        (SELECT f.code FROM country_flag_map f
          WHERE btrim(t."country") LIKE f.flag || '%' ORDER BY length(f.flag) DESC LIMIT 1),
        t."country")`;
  const mapped = blankToNull
    ? `CASE WHEN btrim(t."country") = '' THEN NULL
      ELSE ${lookup}
    END`
    : lookup;
  return `UPDATE "${table}" t SET "country" = s.mapped
FROM (
  SELECT t."id",
    ${mapped} AS mapped
  FROM "${table}" t
  WHERE t."country" IS NOT NULL
) s
WHERE s."id" = t."id" AND s.mapped IS DISTINCT FROM t."country";`;
}

function checkFor(table: string): string {
  return `ALTER TABLE "${table}" ADD CONSTRAINT "${table}_country_format_check"
  CHECK ("country" IS NULL OR "country" ~ '^[A-Z]{2}(-[A-Z]{3})?$') NOT VALID;`;
}

function main() {
  const keys = [...buildKeyMap().entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const flags: [string, string][] = [...COUNTRY_CODES].sort().map((code) => [flagFor(code), code]);

  const sql = `-- GENERATED by prisma/scripts/generate-country-mapping.ts. Do not edit by hand.
--
-- Data migration: User.country, Club.country and JobOpportunity.country become
-- uppercase ISO 3166-1 alpha-2 codes ("AR", "ES") or GB-ENG / GB-SCT / GB-WLS
-- (see src/common/geo/countries.ts). Legacy values were flag emojis, English or
-- Spanish names and free text. Mapping, in order:
--   1. exact match of lower(btrim(value)) (NFC) against codes and en/es/fr names
--   2. value starting with a flag emoji ("🇪🇸", "🇪🇸 España")
--   3. no match: left as is
-- A blank User.country becomes NULL (Club/JobOpportunity.country are NOT NULL).
-- Re-running it changes nothing.

CREATE TEMP TABLE country_key_map (key text PRIMARY KEY, code text NOT NULL);
INSERT INTO country_key_map (key, code) VALUES
${valuesList(keys)};

CREATE TEMP TABLE country_flag_map (flag text PRIMARY KEY, code text NOT NULL);
INSERT INTO country_flag_map (flag, code) VALUES
${valuesList(flags)};

${updateFor("User", true)}

${updateFor("Club", false)}

${updateFor("JobOpportunity", false)}

DROP TABLE country_key_map;
DROP TABLE country_flag_map;

-- Format guard. NOT VALID: enforced for every new INSERT/UPDATE, existing rows
-- are not scanned. Once no legacy value is left run, per table:
--   ALTER TABLE "<table>" VALIDATE CONSTRAINT "<table>_country_format_check";
${checkFor("User")}

${checkFor("Club")}

${checkFor("JobOpportunity")}
`;

  const out = join(__dirname, "..", "migrations", MIGRATION, "migration.sql");
  writeFileSync(out, sql, "utf8");
  process.stdout.write(`Wrote ${out}: ${keys.length} name keys, ${flags.length} flags\n`);
}

main();
